### ISSUE TITLE
IWXXM-US schemas cannot use IWXXM types

### ISSUE THREAD

**Issue by mgoberfield** [NOAA-MDL/iwxxm-us-modelling#3]
Currently IWXXM-US 3.0 metarSpeci schema uses the following XML types in the IWXXM namespace (defined as "http://icao.int/iwxxm/3.0" with prefix 'iwxxm'):

 * MeasureWithNilReason
 * LengthWithNilReason
 * RelationalOperatorType
 * CloudAmountReportedAtAerodromeType
 * AerodromePresentWeatherType
 
An XML document cannot refer to two different URIs having the same namespace prefix, in particular 'iwxxm'.  The duplicate namespace prefix error will occur when IWXXM 2012-2 (defined as "http://icao.int/iwxxm/2021-2") is released and attempts to use it (or any other future release) to construct US IWXXM METAR and SPECI reports which have extension content in them. This will make the XML document invalid.

Therefore, the IWXXM-US schemas will have to duplicate the IWXXM XML types listed above but under the IWXXM-US namespace. This necessitates an IWXXM-US 3.1 release.

**Comment by mdzettlemoyer** [comment]
I briefed the ICAMS Working Group for Observational Data (WG/OD) today (10 June 2021) on this issue. We can proceed with the namespace prefix update.

**Comment by mgoberfield** [comment]
Required changes merged.
